### ISSUE TITLE
Support GraphQL directives to configure models

### ISSUE THREAD

**Issue by maticzav** [prisma/graphql-resolver-codegen#78] opened 2018-10-15 15:08 UTC
Hey 👋,

We thought it would make the most sense to have a direct one-to-one mapping of models and schema type declarations. We also fidgeted a bit with the idea of `@model(path: "pathtomodel.ts:Model")` directive syntax but thought it would be too conventional for the first version, and that we could implement it as this package evolves.

I also added a sample code of our current approach but would love to hear other ideas as well. 🙌 

```yaml
  User: ./src/generated/prisma-client/index.ts:UserNode
  Post: ./src/generated/prisma-client/index.ts:PostNode
```

**Comment by schickling** [comment] 2018-10-15 20:06
Duplicate of https://github.com/prisma/graphql-resolver-codegen/issues/83

**Closed by schickling** 2018-10-15 20:06 UTC
Labels: 0.2, discussion
